// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_fst_c.h"
#include "Vtop__Syms.h"


VL_ATTR_COLD void Vtop___024root__trace_init_sub__TOP__0(Vtop___024root* vlSelf, VerilatedFst* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_sub__TOP__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+116,"clk",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+117,"linetrace",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->pushNamePrefix("top ");
    tracep->declBit(c+116,"clk",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+117,"linetrace",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+1,"reset",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+39,"imem_reqstream_val",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+119,"imem_reqstream_rdy",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+2,"imem_respstream_val",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+40,"imem_respstream_rdy",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+41,"imem_respstream_drop",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+42,"dmem_reqstream_val",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+14,"dmem_reqstream_rdy",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+15,"dmem_respstream_val",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+43,"dmem_respstream_rdy",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+84,"mem_action_M",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+16,"mngr2proc_val",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+44,"mngr2proc_rdy",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+45,"proc2mngr_val",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+17,"proc2mngr_rdy",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+40,"reg_en_F",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+46,"pc_sel_F",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->declBit(c+47,"reg_en_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+19,"op1_sel_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+20,"op2_sel_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->declBus(c+21,"csrr_sel_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->declBus(c+22,"imm_type_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
    tracep->declBit(c+48,"reg_en_X",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+85,"alu_fn_X",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 3,0);
    tracep->declBus(c+86,"ex_result_sel_X",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->declBit(c+49,"reg_en_M",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+87,"wb_result_sel_M",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+50,"reg_en_W",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+88,"rf_waddr_W",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 4,0);
    tracep->declBit(c+89,"rf_wen_W",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+90,"stats_en_wen_W",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+51,"imul_req_val_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+52,"imul_resp_rdy_X",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+3,"inst_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBit(c+4,"br_cond_eq_X",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+5,"br_cond_lt_X",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+18,"br_cond_ltu_X",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+6,"imul_req_rdy_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+118,"imul_resp_val_X",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+53,"commit_inst",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+120,"n",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 0,0);
    tracep->declBus(c+121,"y",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 0,0);
    tracep->declBus(c+122,"rx",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 4,0);
    tracep->declBus(c+122,"r0",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 4,0);
    tracep->declBus(c+123,"rL",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 4,0);
    tracep->declBus(c+124,"j_x",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 1,0);
    tracep->declBus(c+124,"j_na",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 1,0);
    tracep->declBus(c+125,"j_jal",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 1,0);
    tracep->declBus(c+126,"j_jalr",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 1,0);
    tracep->declBus(c+127,"br_x",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 2,0);
    tracep->declBus(c+127,"br_na",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 2,0);
    tracep->declBus(c+128,"br_bne",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 2,0);
    tracep->declBus(c+129,"br_beq",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 2,0);
    tracep->declBus(c+130,"br_blt",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 2,0);
    tracep->declBus(c+131,"br_bltu",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 2,0);
    tracep->declBus(c+132,"br_bge",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 2,0);
    tracep->declBus(c+133,"br_bgeu",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 2,0);
    tracep->declBus(c+120,"bm1_x",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 0,0);
    tracep->declBus(c+120,"bm1_pc",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 0,0);
    tracep->declBus(c+121,"bm1_rf",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 0,0);
    tracep->declBus(c+124,"bm2_x",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 1,0);
    tracep->declBus(c+124,"bm2_imm",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 1,0);
    tracep->declBus(c+125,"bm2_rf",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 1,0);
    tracep->declBus(c+126,"bm2_csr",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 1,0);
    tracep->declBus(c+124,"ex_x",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 1,0);
    tracep->declBus(c+124,"ex_pc",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 1,0);
    tracep->declBus(c+125,"ex_alu",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 1,0);
    tracep->declBus(c+126,"ex_imul",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 1,0);
    tracep->declBus(c+134,"alu_x",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 3,0);
    tracep->declBus(c+134,"alu_add",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 3,0);
    tracep->declBus(c+135,"alu_sub",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 3,0);
    tracep->declBus(c+136,"alu_and",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 3,0);
    tracep->declBus(c+137,"alu_or",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 3,0);
    tracep->declBus(c+138,"alu_xor",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 3,0);
    tracep->declBus(c+139,"alu_slt",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 3,0);
    tracep->declBus(c+140,"alu_sltu",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 3,0);
    tracep->declBus(c+141,"alu_sra",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 3,0);
    tracep->declBus(c+142,"alu_srl",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 3,0);
    tracep->declBus(c+143,"alu_sll",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 3,0);
    tracep->declBus(c+144,"alu_cp0",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 3,0);
    tracep->declBus(c+145,"alu_cp1",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 3,0);
    tracep->declBus(c+127,"imm_x",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 2,0);
    tracep->declBus(c+127,"imm_i",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 2,0);
    tracep->declBus(c+128,"imm_s",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 2,0);
    tracep->declBus(c+129,"imm_b",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 2,0);
    tracep->declBus(c+130,"imm_u",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 2,0);
    tracep->declBus(c+131,"imm_j",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 2,0);
    tracep->declBus(c+124,"nr",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 1,0);
    tracep->declBus(c+125,"ld",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 1,0);
    tracep->declBus(c+126,"st",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 1,0);
    tracep->declBus(c+120,"wm_x",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 0,0);
    tracep->declBus(c+120,"wm_a",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 0,0);
    tracep->declBus(c+121,"wm_m",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 0,0);
    tracep->pushNamePrefix("DUT ");
    tracep->declBit(c+116,"clk",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+1,"reset",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+39,"imem_reqstream_val",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+119,"imem_reqstream_rdy",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+2,"imem_respstream_val",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+40,"imem_respstream_rdy",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+41,"imem_respstream_drop",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+42,"dmem_reqstream_val",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+14,"dmem_reqstream_rdy",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+15,"dmem_respstream_val",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+43,"dmem_respstream_rdy",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+84,"mem_action_M",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+16,"mngr2proc_val",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+44,"mngr2proc_rdy",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+45,"proc2mngr_val",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+17,"proc2mngr_rdy",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+40,"reg_en_F",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+46,"pc_sel_F",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBit(c+47,"reg_en_D",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+19,"op1_sel_D",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+20,"op2_sel_D",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+21,"csrr_sel_D",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+22,"imm_type_D",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBit(c+51,"imul_req_val_D",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+48,"reg_en_X",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+85,"alu_fn_X",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+86,"ex_result_sel_X",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBit(c+49,"reg_en_M",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+87,"wb_result_sel_M",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+50,"reg_en_W",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+88,"rf_waddr_W",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBit(c+89,"rf_wen_W",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+90,"stats_en_wen_W",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+52,"imul_resp_rdy_X",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+3,"inst_D",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+6,"imul_req_rdy_D",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+4,"br_cond_eq_X",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+5,"br_cond_lt_X",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+18,"br_cond_ltu_X",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+118,"imul_resp_val_X",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+53,"commit_inst",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+91,"val_F",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+92,"val_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+93,"val_X",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+94,"val_M",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+95,"val_W",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+54,"ostall_F",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+55,"ostall_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+56,"ostall_X",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+57,"ostall_M",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+58,"ostall_W",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+59,"stall_F",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+60,"stall_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+61,"stall_X",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+62,"stall_M",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+63,"stall_W",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+64,"osquash_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+65,"osquash_X",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+41,"squash_F",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+66,"squash_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+67,"pc_redirect_X",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+96,"pc_sel_X",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->declBus(c+68,"pc_sel_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->declBit(c+69,"next_val_F",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+7,"inst_rd_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 4,0);
    tracep->declBus(c+8,"inst_rs1_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 4,0);
    tracep->declBus(c+9,"inst_rs2_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 4,0);
    tracep->declBus(c+10,"inst_csr_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 11,0);
    tracep->declBus(c+120,"n",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 0,0);
    tracep->declBus(c+121,"y",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 0,0);
    tracep->declBus(c+122,"rx",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 4,0);
    tracep->declBus(c+122,"r0",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 4,0);
    tracep->declBus(c+123,"rL",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 4,0);
    tracep->declBus(c+124,"j_x",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 1,0);
    tracep->declBus(c+124,"j_na",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 1,0);
    tracep->declBus(c+125,"j_jal",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 1,0);
    tracep->declBus(c+126,"j_jalr",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 1,0);
    tracep->declBus(c+127,"br_x",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 2,0);
    tracep->declBus(c+127,"br_na",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 2,0);
    tracep->declBus(c+128,"br_bne",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 2,0);
    tracep->declBus(c+129,"br_beq",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 2,0);
    tracep->declBus(c+130,"br_blt",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 2,0);
    tracep->declBus(c+131,"br_bltu",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 2,0);
    tracep->declBus(c+132,"br_bge",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 2,0);
    tracep->declBus(c+133,"br_bgeu",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 2,0);
    tracep->declBus(c+120,"bm1_x",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 0,0);
    tracep->declBus(c+120,"bm1_pc",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 0,0);
    tracep->declBus(c+121,"bm1_rf",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 0,0);
    tracep->declBus(c+124,"bm2_x",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 1,0);
    tracep->declBus(c+124,"bm2_imm",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 1,0);
    tracep->declBus(c+125,"bm2_rf",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 1,0);
    tracep->declBus(c+126,"bm2_csr",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 1,0);
    tracep->declBus(c+124,"ex_x",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 1,0);
    tracep->declBus(c+124,"ex_pc",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 1,0);
    tracep->declBus(c+125,"ex_alu",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 1,0);
    tracep->declBus(c+126,"ex_imul",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 1,0);
    tracep->declBus(c+134,"alu_x",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 3,0);
    tracep->declBus(c+134,"alu_add",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 3,0);
    tracep->declBus(c+135,"alu_sub",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 3,0);
    tracep->declBus(c+136,"alu_and",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 3,0);
    tracep->declBus(c+137,"alu_or",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 3,0);
    tracep->declBus(c+138,"alu_xor",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 3,0);
    tracep->declBus(c+139,"alu_slt",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 3,0);
    tracep->declBus(c+140,"alu_sltu",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 3,0);
    tracep->declBus(c+141,"alu_sra",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 3,0);
    tracep->declBus(c+142,"alu_srl",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 3,0);
    tracep->declBus(c+143,"alu_sll",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 3,0);
    tracep->declBus(c+144,"alu_cp0",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 3,0);
    tracep->declBus(c+145,"alu_cp1",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 3,0);
    tracep->declBus(c+127,"imm_x",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 2,0);
    tracep->declBus(c+127,"imm_i",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 2,0);
    tracep->declBus(c+128,"imm_s",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 2,0);
    tracep->declBus(c+129,"imm_b",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 2,0);
    tracep->declBus(c+130,"imm_u",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 2,0);
    tracep->declBus(c+131,"imm_j",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 2,0);
    tracep->declBus(c+124,"nr",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 1,0);
    tracep->declBus(c+125,"ld",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 1,0);
    tracep->declBus(c+126,"st",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 1,0);
    tracep->declBus(c+120,"wm_x",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 0,0);
    tracep->declBus(c+120,"wm_a",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 0,0);
    tracep->declBus(c+121,"wm_m",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 0,0);
    tracep->declBit(c+23,"inst_val_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+24,"j_type_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->declBus(c+25,"br_type_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
    tracep->declBit(c+26,"rs1_en_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+27,"rs2_en_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+28,"alu_fn_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 3,0);
    tracep->declBus(c+29,"ex_result_sel_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->declBit(c+30,"mul_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+31,"dmem_reqstream_type_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->declBit(c+32,"wb_result_sel_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+33,"rf_wen_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+34,"csrr_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+35,"csrw_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+36,"proc2mngr_val_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+37,"mngr2proc_rdy_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+38,"stats_en_wen_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+70,"pc_redirect_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+7,"rf_waddr_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 4,0);
    tracep->declBit(c+71,"ostall_mngr2proc_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+72,"ostall_waddr_X_rs1_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+73,"ostall_waddr_M_rs1_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+74,"ostall_waddr_W_rs1_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+75,"ostall_waddr_X_rs2_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+76,"ostall_waddr_M_rs2_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+77,"ostall_waddr_W_rs2_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+11,"ostall_imul_req_rdy_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+78,"ostall_hazard_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+79,"next_val_D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+97,"inst_X",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBus(c+98,"dmem_reqstream_type_X",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->declBit(c+99,"wb_result_sel_X",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+100,"rf_wen_X",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+101,"rf_waddr_X",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 4,0);
    tracep->declBit(c+102,"proc2mngr_val_X",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+103,"stats_en_wen_X",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+104,"br_type_X",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
    tracep->declBus(c+105,"j_type_X",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->declBit(c+80,"ostall_imul_resp_val_X",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+81,"ostall_dmem_reqstream_X",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+82,"next_val_X",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+106,"inst_M",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBus(c+107,"dmem_reqstream_type_M",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->declBit(c+108,"rf_wen_M",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+109,"rf_waddr_M",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 4,0);
    tracep->declBit(c+110,"proc2mngr_val_M",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+111,"stats_en_wen_M",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+83,"next_val_M",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+112,"inst_W",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBit(c+113,"proc2mngr_val_W",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+114,"rf_wen_pending_W",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+115,"stats_en_wen_pending_W",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->pushNamePrefix("inst_unpack ");
    tracep->declBus(c+3,"inst",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+12,"opcode",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 6,0);
    tracep->declBus(c+7,"rd",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+8,"rs1",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+9,"rs2",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+13,"funct3",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+146,"funct7",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 6,0);
    tracep->declBus(c+10,"csr",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 11,0);
    tracep->popNamePrefix(3);
}

VL_ATTR_COLD void Vtop___024root__trace_init_top(Vtop___024root* vlSelf, VerilatedFst* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_top\n"); );
    // Body
    Vtop___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vtop___024root__trace_full_top_0(void* voidSelf, VerilatedFst::Buffer* bufp);
void Vtop___024root__trace_chg_top_0(void* voidSelf, VerilatedFst::Buffer* bufp);
void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedFst* /*unused*/);

VL_ATTR_COLD void Vtop___024root__trace_register(Vtop___024root* vlSelf, VerilatedFst* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_register\n"); );
    // Body
    tracep->addFullCb(&Vtop___024root__trace_full_top_0, vlSelf);
    tracep->addChgCb(&Vtop___024root__trace_chg_top_0, vlSelf);
    tracep->addCleanupCb(&Vtop___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vtop___024root__trace_full_sub_0(Vtop___024root* vlSelf, VerilatedFst::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_full_top_0(void* voidSelf, VerilatedFst::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_top_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtop___024root__trace_full_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_full_sub_0(Vtop___024root* vlSelf, VerilatedFst::Buffer* bufp) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_sub_0\n"); );
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullBit(oldp+1,(vlSelf->top__DOT__reset));
    bufp->fullBit(oldp+2,(vlSelf->top__DOT__imem_respstream_val));
    bufp->fullIData(oldp+3,(vlSelf->top__DOT__inst_D),32);
    bufp->fullBit(oldp+4,(vlSelf->top__DOT__br_cond_eq_X));
    bufp->fullBit(oldp+5,(vlSelf->top__DOT__br_cond_lt_X));
    bufp->fullBit(oldp+6,(vlSelf->top__DOT__imul_req_rdy_D));
    bufp->fullCData(oldp+7,((0x1fU & (vlSelf->top__DOT__inst_D 
                                      >> 7U))),5);
    bufp->fullCData(oldp+8,((0x1fU & (vlSelf->top__DOT__inst_D 
                                      >> 0xfU))),5);
    bufp->fullCData(oldp+9,((0x1fU & (vlSelf->top__DOT__inst_D 
                                      >> 0x14U))),5);
    bufp->fullSData(oldp+10,((vlSelf->top__DOT__inst_D 
                              >> 0x14U)),12);
    bufp->fullBit(oldp+11,((1U & (~ (IData)(vlSelf->top__DOT__imul_req_rdy_D)))));
    bufp->fullCData(oldp+12,((0x7fU & vlSelf->top__DOT__inst_D)),7);
    bufp->fullCData(oldp+13,((7U & (vlSelf->top__DOT__inst_D 
                                    >> 0xcU))),3);
    bufp->fullBit(oldp+14,(vlSelf->top__DOT__dmem_reqstream_rdy));
    bufp->fullBit(oldp+15,(vlSelf->top__DOT__dmem_respstream_val));
    bufp->fullBit(oldp+16,(vlSelf->top__DOT__mngr2proc_val));
    bufp->fullBit(oldp+17,(vlSelf->top__DOT__proc2mngr_rdy));
    bufp->fullBit(oldp+18,(vlSelf->top__DOT__br_cond_ltu_X));
    bufp->fullBit(oldp+19,(vlSelf->top__DOT__op1_sel_D));
    bufp->fullCData(oldp+20,(vlSelf->top__DOT__op2_sel_D),2);
    bufp->fullCData(oldp+21,(vlSelf->top__DOT__csrr_sel_D),2);
    bufp->fullCData(oldp+22,(vlSelf->top__DOT__imm_type_D),3);
    bufp->fullBit(oldp+23,(vlSelf->top__DOT__DUT__DOT__inst_val_D));
    bufp->fullCData(oldp+24,(vlSelf->top__DOT__DUT__DOT__j_type_D),2);
    bufp->fullCData(oldp+25,(vlSelf->top__DOT__DUT__DOT__br_type_D),3);
    bufp->fullBit(oldp+26,(vlSelf->top__DOT__DUT__DOT__rs1_en_D));
    bufp->fullBit(oldp+27,(vlSelf->top__DOT__DUT__DOT__rs2_en_D));
    bufp->fullCData(oldp+28,(vlSelf->top__DOT__DUT__DOT__alu_fn_D),4);
    bufp->fullCData(oldp+29,(vlSelf->top__DOT__DUT__DOT__ex_result_sel_D),2);
    bufp->fullBit(oldp+30,(vlSelf->top__DOT__DUT__DOT__mul_D));
    bufp->fullCData(oldp+31,(vlSelf->top__DOT__DUT__DOT__dmem_reqstream_type_D),2);
    bufp->fullBit(oldp+32,(vlSelf->top__DOT__DUT__DOT__wb_result_sel_D));
    bufp->fullBit(oldp+33,(vlSelf->top__DOT__DUT__DOT__rf_wen_D));
    bufp->fullBit(oldp+34,(vlSelf->top__DOT__DUT__DOT__csrr_D));
    bufp->fullBit(oldp+35,(vlSelf->top__DOT__DUT__DOT__csrw_D));
    bufp->fullBit(oldp+36,(vlSelf->top__DOT__DUT__DOT__proc2mngr_val_D));
    bufp->fullBit(oldp+37,(vlSelf->top__DOT__DUT__DOT__mngr2proc_rdy_D));
    bufp->fullBit(oldp+38,(vlSelf->top__DOT__DUT__DOT__stats_en_wen_D));
    bufp->fullBit(oldp+39,(vlSelf->top__DOT__imem_reqstream_val));
    bufp->fullBit(oldp+40,(vlSelf->top__DOT__imem_respstream_rdy));
    bufp->fullBit(oldp+41,(vlSelf->top__DOT__DUT__DOT__squash_F));
    bufp->fullBit(oldp+42,(vlSelf->top__DOT__dmem_reqstream_val));
    bufp->fullBit(oldp+43,(vlSelf->top__DOT__dmem_respstream_rdy));
    bufp->fullBit(oldp+44,(vlSelf->top__DOT__mngr2proc_rdy));
    bufp->fullBit(oldp+45,(vlSelf->top__DOT__proc2mngr_val));
    bufp->fullCData(oldp+46,(vlSelf->top__DOT__pc_sel_F),2);
    bufp->fullBit(oldp+47,(vlSelf->top__DOT__reg_en_D));
    bufp->fullBit(oldp+48,((1U & (~ (IData)(vlSelf->top__DOT__DUT__DOT__stall_X)))));
    bufp->fullBit(oldp+49,((1U & (~ (IData)(vlSelf->top__DOT__DUT__DOT__stall_M)))));
    bufp->fullBit(oldp+50,((1U & (~ (IData)(vlSelf->top__DOT__DUT__DOT__stall_W)))));
    bufp->fullBit(oldp+51,(vlSelf->top__DOT__imul_req_val_D));
    bufp->fullBit(oldp+52,(vlSelf->top__DOT__imul_resp_rdy_X));
    bufp->fullBit(oldp+53,(vlSelf->top__DOT__commit_inst));
    bufp->fullBit(oldp+54,(vlSelf->top__DOT__DUT__DOT__ostall_F));
    bufp->fullBit(oldp+55,(vlSelf->top__DOT__DUT__DOT__ostall_D));
    bufp->fullBit(oldp+56,(vlSelf->top__DOT__DUT__DOT__ostall_X));
    bufp->fullBit(oldp+57,(vlSelf->top__DOT__DUT__DOT__ostall_M));
    bufp->fullBit(oldp+58,(vlSelf->top__DOT__DUT__DOT__ostall_W));
    bufp->fullBit(oldp+59,(vlSelf->top__DOT__DUT__DOT__stall_F));
    bufp->fullBit(oldp+60,(vlSelf->top__DOT__DUT__DOT__stall_D));
    bufp->fullBit(oldp+61,(vlSelf->top__DOT__DUT__DOT__stall_X));
    bufp->fullBit(oldp+62,(vlSelf->top__DOT__DUT__DOT__stall_M));
    bufp->fullBit(oldp+63,(vlSelf->top__DOT__DUT__DOT__stall_W));
    bufp->fullBit(oldp+64,(vlSelf->top__DOT__DUT__DOT__osquash_D));
    bufp->fullBit(oldp+65,(vlSelf->top__DOT__DUT__DOT__osquash_X));
    bufp->fullBit(oldp+66,(vlSelf->top__DOT__DUT__DOT__squash_D));
    bufp->fullBit(oldp+67,(vlSelf->top__DOT__DUT__DOT__pc_redirect_X));
    bufp->fullCData(oldp+68,(vlSelf->top__DOT__DUT__DOT__pc_sel_D),2);
    bufp->fullBit(oldp+69,(vlSelf->top__DOT__DUT__DOT__next_val_F));
    bufp->fullBit(oldp+70,(vlSelf->top__DOT__DUT__DOT__pc_redirect_D));
    bufp->fullBit(oldp+71,(vlSelf->top__DOT__DUT__DOT__ostall_mngr2proc_D));
    bufp->fullBit(oldp+72,(vlSelf->top__DOT__DUT__DOT__ostall_waddr_X_rs1_D));
    bufp->fullBit(oldp+73,(vlSelf->top__DOT__DUT__DOT__ostall_waddr_M_rs1_D));
    bufp->fullBit(oldp+74,(vlSelf->top__DOT__DUT__DOT__ostall_waddr_W_rs1_D));
    bufp->fullBit(oldp+75,(vlSelf->top__DOT__DUT__DOT__ostall_waddr_X_rs2_D));
    bufp->fullBit(oldp+76,(vlSelf->top__DOT__DUT__DOT__ostall_waddr_M_rs2_D));
    bufp->fullBit(oldp+77,(vlSelf->top__DOT__DUT__DOT__ostall_waddr_W_rs2_D));
    bufp->fullBit(oldp+78,(vlSelf->top__DOT__DUT__DOT__ostall_hazard_D));
    bufp->fullBit(oldp+79,(vlSelf->top__DOT__DUT__DOT__next_val_D));
    bufp->fullBit(oldp+80,(vlSelf->top__DOT__DUT__DOT__ostall_imul_resp_val_X));
    bufp->fullBit(oldp+81,(vlSelf->top__DOT__DUT__DOT__ostall_dmem_reqstream_X));
    bufp->fullBit(oldp+82,(vlSelf->top__DOT__DUT__DOT__next_val_X));
    bufp->fullBit(oldp+83,(vlSelf->top__DOT__DUT__DOT__next_val_M));
    bufp->fullBit(oldp+84,(vlSelf->top__DOT__mem_action_M));
    bufp->fullCData(oldp+85,(vlSelf->top__DOT__alu_fn_X),4);
    bufp->fullCData(oldp+86,(vlSelf->top__DOT__ex_result_sel_X),2);
    bufp->fullBit(oldp+87,(vlSelf->top__DOT__wb_result_sel_M));
    bufp->fullCData(oldp+88,(vlSelf->top__DOT__rf_waddr_W),5);
    bufp->fullBit(oldp+89,(vlSelf->top__DOT__rf_wen_W));
    bufp->fullBit(oldp+90,(vlSelf->top__DOT__stats_en_wen_W));
    bufp->fullBit(oldp+91,(vlSelf->top__DOT__DUT__DOT__val_F));
    bufp->fullBit(oldp+92,(vlSelf->top__DOT__DUT__DOT__val_D));
    bufp->fullBit(oldp+93,(vlSelf->top__DOT__DUT__DOT__val_X));
    bufp->fullBit(oldp+94,(vlSelf->top__DOT__DUT__DOT__val_M));
    bufp->fullBit(oldp+95,(vlSelf->top__DOT__DUT__DOT__val_W));
    bufp->fullCData(oldp+96,(vlSelf->top__DOT__DUT__DOT__pc_sel_X),2);
    bufp->fullIData(oldp+97,(vlSelf->top__DOT__DUT__DOT__inst_X),32);
    bufp->fullCData(oldp+98,(vlSelf->top__DOT__DUT__DOT__dmem_reqstream_type_X),2);
    bufp->fullBit(oldp+99,(vlSelf->top__DOT__DUT__DOT__wb_result_sel_X));
    bufp->fullBit(oldp+100,(vlSelf->top__DOT__DUT__DOT__rf_wen_X));
    bufp->fullCData(oldp+101,(vlSelf->top__DOT__DUT__DOT__rf_waddr_X),5);
    bufp->fullBit(oldp+102,(vlSelf->top__DOT__DUT__DOT__proc2mngr_val_X));
    bufp->fullBit(oldp+103,(vlSelf->top__DOT__DUT__DOT__stats_en_wen_X));
    bufp->fullCData(oldp+104,(vlSelf->top__DOT__DUT__DOT__br_type_X),3);
    bufp->fullCData(oldp+105,(vlSelf->top__DOT__DUT__DOT__j_type_X),2);
    bufp->fullIData(oldp+106,(vlSelf->top__DOT__DUT__DOT__inst_M),32);
    bufp->fullCData(oldp+107,(vlSelf->top__DOT__DUT__DOT__dmem_reqstream_type_M),2);
    bufp->fullBit(oldp+108,(vlSelf->top__DOT__DUT__DOT__rf_wen_M));
    bufp->fullCData(oldp+109,(vlSelf->top__DOT__DUT__DOT__rf_waddr_M),5);
    bufp->fullBit(oldp+110,(vlSelf->top__DOT__DUT__DOT__proc2mngr_val_M));
    bufp->fullBit(oldp+111,(vlSelf->top__DOT__DUT__DOT__stats_en_wen_M));
    bufp->fullIData(oldp+112,(vlSelf->top__DOT__DUT__DOT__inst_W),32);
    bufp->fullBit(oldp+113,(vlSelf->top__DOT__DUT__DOT__proc2mngr_val_W));
    bufp->fullBit(oldp+114,(vlSelf->top__DOT__DUT__DOT__rf_wen_pending_W));
    bufp->fullBit(oldp+115,(vlSelf->top__DOT__DUT__DOT__stats_en_wen_pending_W));
    bufp->fullBit(oldp+116,(vlSelf->clk));
    bufp->fullBit(oldp+117,(vlSelf->linetrace));
    bufp->fullBit(oldp+118,(vlSelf->top__DOT__imul_resp_val_X));
    bufp->fullBit(oldp+119,(vlSelf->top__DOT__imem_reqstream_rdy));
    bufp->fullBit(oldp+120,(0U));
    bufp->fullBit(oldp+121,(1U));
    bufp->fullCData(oldp+122,(0U),5);
    bufp->fullCData(oldp+123,(0x1fU),5);
    bufp->fullCData(oldp+124,(0U),2);
    bufp->fullCData(oldp+125,(1U),2);
    bufp->fullCData(oldp+126,(2U),2);
    bufp->fullCData(oldp+127,(0U),3);
    bufp->fullCData(oldp+128,(1U),3);
    bufp->fullCData(oldp+129,(2U),3);
    bufp->fullCData(oldp+130,(3U),3);
    bufp->fullCData(oldp+131,(4U),3);
    bufp->fullCData(oldp+132,(5U),3);
    bufp->fullCData(oldp+133,(6U),3);
    bufp->fullCData(oldp+134,(0U),4);
    bufp->fullCData(oldp+135,(1U),4);
    bufp->fullCData(oldp+136,(2U),4);
    bufp->fullCData(oldp+137,(3U),4);
    bufp->fullCData(oldp+138,(4U),4);
    bufp->fullCData(oldp+139,(5U),4);
    bufp->fullCData(oldp+140,(6U),4);
    bufp->fullCData(oldp+141,(7U),4);
    bufp->fullCData(oldp+142,(8U),4);
    bufp->fullCData(oldp+143,(9U),4);
    bufp->fullCData(oldp+144,(0xbU),4);
    bufp->fullCData(oldp+145,(0xcU),4);
    bufp->fullCData(oldp+146,(vlSelf->top__DOT__DUT__DOT__inst_unpack__DOT__funct7),7);
}
